import Head from 'next/head';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
config.autoAddCss = false;

//import '@/styles/globals.css';

const theme = createTheme({
  palette: {
    primary: {
      main: '#E91E63', // Coloca aquí el color principal que desees
    },
    secondary: {
      main: '#2B2E4A', // Coloca aquí el color secundario que desees
    },
  },
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>NOMADAPP</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/img/logo3.svg' />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
}
