import Head from 'next/head';
import NavbarTwo from "@/components/Navbar/NavbarTwo";
import HeroImage from "@/components/Itinerary/HeroImage";
import FlightCard from '@/components/Itinerary/FlightCard';

import Footer from "@/components/Footer/Footer";

import { flightData } from '@/components/Itinerary/flightData';


export default function itinerary() {
    return(
        <>
            <Head>
                <title>Nomada</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/img/logo1.svg' />
            </Head>
            <NavbarTwo/>

            <HeroImage/>

            <FlightCard flightData={flightData}/>

            <Footer/>
            
        </>
    )
}