import Head from 'next/head';
import NavbarTwo from '@/components/Navbar/NavbarTwo';
import HeroImage from '@/components/Itinerary/HeroImage';
import FlightCard from '@/components/Itinerary/FlightCard';
import HotelCard from '@/components/Itinerary/HotelCard';
import ActivityCard from '@/components/Itinerary/ActivityCard';
import axios from 'axios';
import Footer from '@/components/Footer/Footer';

import { flightData } from '@/components/Itinerary/flightData';
import { hotelData } from '@/components/Itinerary/hotelData';
import { activityData } from '@/components/Itinerary/activityData';

import Box from '@mui/material/Box';

export default function Itinerary({ contentViaje = [] }) {
  console.log(contentViaje);
  return (
    <>
      <Head>
        <title>Nomada</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/img/logo1.svg' />
      </Head>
      <NavbarTwo />

      <HeroImage />

      <Box
        sx={{
          margin: 5,
        }}
      >
        <FlightCard flightData={flightData} />

        <HotelCard hotelData={hotelData} />

        <ActivityCard activityData={activityData} />
      </Box>

      <Footer />
    </>
  );
}

export const getServerSideProps = async () => {
  let contentViaje = [];
  try {
    contentViaje = await axios.get('https://nomada-backend-production.up.railway.app/api/v1/viajes');
    console.log('statusCode', contentViaje.status);

    return {
      props: {
        contentViaje: contentViaje.data,
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        contentViaje: {},
      },
    };
  }
};
