import Head from 'next/head';
import CardDetalle from '../components/Add/CardDetalle';
import { dataTwo } from '../components/Add/dataTwo';

export default function Prueba() {
  return (
    <>
      <Head>
        <title>Nomada</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/img/logo1.svg' />
      </Head>

      <CardDetalle data={dataTwo} />
    </>
  );
}
