import Head from 'next/head';
import NavbarTwo from '@/components/Navbar/NavbarTwo';
import SearchBar from '@/components/Search/Search';
import MapButton from '@/components/common/MapButton';
import { cityData } from '@/components/Search/cityData';
import RestaurantCard from '@/components/Search/RestaurantCard';
import { restaurantData } from '@/components/Search/restaurantData';
import Footer from '@/components/Footer/Footer';
//import Spinner from '@/components/common/Spinner';
//import axios from 'axios';
//import React, { useEffect, useState } from 'react';

import Box from '@mui/material/Box';
import CityCard from '@/components/Search/cityCard';
import axios from 'axios';

export default function Search({ contentApi = [] }) {
  console.log('getInitialProps', contentApi);

  return (
    <>
      <Head>
        <title>Nomada</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/img/logo1.svg' />
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css'
        />
      </Head>
      <NavbarTwo />

      <SearchBar />

      <Box>
        {
          /*contentApi === undefined || contentApi.lengh === 0 ? <Spinner/> :*/
          <CityCard contentApi={cityData} />
        }
      </Box>
      <Box>
        {
          /*contentApi === undefined || contentApi.lengh === 0 ? <Spinner/> :*/
          <RestaurantCard restaurantData={restaurantData.data} />
        }
      </Box>

      <Box sx={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <MapButton />
        <div>{contentApi}</div>
      </Box>

      <Footer />
    </>
  );
}

Search.getInitialProps = async () => {
  let contentApi = [];
  try {
    const response = await axios.get('/api/proxy/restaurantSearch');
    contentApi = response.data;
  } catch (error) {
    console.error(error);
  }

  return { contentApi };
};
