export const restaurantData = {
  data: [
    {
      location_id: '24064537',
      name: 'In-n-out Coffee',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Av. Kohunlich Retorno 3-a',
        street2: '40',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77533',
        address_string: 'Av. Kohunlich Retorno 3-a 40, Cancun 77533 Mexico',
      },
    },
    {
      location_id: '25126761',
      name: 'Tuscany Trattoria',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Blvd. Kukulcan Km. 9.5, Zona Hotelera',
        street2: 'Grand Fiesta Americana Coral Beach Cancún All Inclusive Spa Resort',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77500',
        address_string:
          'Blvd. Kukulcan Km. 9.5, Zona Hotelera Grand Fiesta Americana Coral Beach Cancún All Inclusive Spa Resort, Cancun 77500 Mexico',
      },
    },
    {
      location_id: '25073541',
      name: 'She Restaurant',
      distance: '0.6110568532169931',
      bearing: 'east',
      address_obj: {
        street1: 'Boulevard Kukulkan Km 3.5',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77500',
        address_string: 'Boulevard Kukulkan Km 3.5, Cancun 77500 Mexico',
      },
    },
    {
      location_id: '1381047',
      name: 'Cocos and Grill',
      distance: '0.621541149628273',
      bearing: 'east',
      address_obj: {
        street1: 'Blvd Kukulcan KM.3.2',
        street2: 'Inside Marina Chac chi',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77500',
        address_string: 'Blvd Kukulcan KM.3.2 Inside Marina Chac chi, Cancun 77500 Mexico',
      },
    },
    {
      location_id: '23559275',
      name: 'Magichal Buenos Dias',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Sm41, Mz 5, L1, Entre Av. Tikal Calle Sagitario',
        street2: 'Num 201 B',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77507',
        address_string: 'Sm41, Mz 5, L1, Entre Av. Tikal Calle Sagitario Num 201 B, Cancun 77507 Mexico',
      },
    },
    {
      location_id: '23484070',
      name: 'Marlin House',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Calle Alcatraces Lt 43',
        street2: 'Local 1, 22',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77500',
        address_string: 'Calle Alcatraces Lt 43 Local 1, 22, Cancun 77500 Mexico',
      },
    },
    {
      location_id: '23878708',
      name: 'Cafe Del Cofre',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Av. Sayil Esq Con Av. Savignac, Malecon Tajamar',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77500',
        address_string: 'Av. Sayil Esq Con Av. Savignac, Malecon Tajamar, Cancun 77500 Mexico',
      },
    },
    {
      location_id: '23593994',
      name: 'Mariscos Camaron & Limon',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Av. Andres Quintana Roo Mz 14-Lote 6 97',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77533',
        address_string: 'Av. Andres Quintana Roo Mz 14-Lote 6 97, Cancun 77533 Mexico',
      },
    },
    {
      location_id: '25079316',
      name: 'Saborines Artesanales Del 23',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Calle Jabin 9',
        street2: 'Mercado 23',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77560',
        address_string: 'Calle Jabin 9 Mercado 23, Cancun 77560 Mexico',
      },
    },
    {
      location_id: '25184948',
      name: 'Tacos And Tequila',
      distance: '0.0',
      bearing: 'northeast',
      address_obj: {
        street1: 'Blvd. Kukulcan Km 15',
        city: 'Cancun',
        state: 'Quintana Roo',
        country: 'Mexico',
        postalcode: '77500',
        address_string: 'Blvd. Kukulcan Km 15, Cancun 77500 Mexico',
      },
    },
  ],
};
