export const flightData = [
  {
    id: 1,
    origin: 'Ciudad de Mexico',
    destination: 'Cancún',
    date: '23-04-2023',
    airline: 'Volaris',
    departureTime: '12:32',
    arrivalTime: '15:35',
    duration: '3:02',
    stops: '0',
    status: 'on Time',
    flightNumber: 'AV-2453',
    terminal: 'T2',
    gate: 'B-21',
    class: 'Economy',
  },
  {
    id: 2,
    origin: 'Cancún',
    destination: 'Ciudad de Mexico',
    date: '30-04-2023',
    airline: 'Volaris',
    departureTime: '10:32',
    arrivalTime: '13:35',
    duration: '3:02',
    stops: '0',
    status: 'on Time',
    flightNumber: 'AV-0544',
    terminal: 'T1',
    gate: '07',
    class: 'Economy',
  },
];
